project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - projects.qmd
    - projects/*.qmd
    - internships/*.qmd
  
website:
  page-navigation: true
  title: "刘俊言"
  site-url: https://liuforge.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/liuforge/liuforge.github.io
  search: false
  
  page-footer:
    left: |
      刘俊言 · Algorithm Engineer<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#f5efe6"
    right: 
      - text: "首页"
        href: index.qmd
      - text: "项目"
        href: projects.qmd

format:
  html:
    theme: styles.scss
    toc: false
